portifolio version 2
looh16/Portfolio pull request #2
Opened 2022-05-28 18:20 UTC by looh16

2022-05-28 19:26 UTC, gtekle requested changes
Hi @looh16 :wave: , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost-there-01](https://user-images.githubusercontent.com/44057863/170839926-9e93ade6-7818-4c14-bc6a-17182442b0c5.gif)


## Highlights
:heavy_check_mark: Good use of Github flow
:heavy_check_mark: Professional Readme

## Required Changes ♻️
_Check the comments under the review._

- [ ] You should use a more descriptive pull request title that shows the changes that are included in this pull request. For example, you could use the title of the activity as PR title. `Portfolio: mobile version` 

- [ ] You should add a descriptive pull request summary that show a summary of the changes introduced in the pull request. Kindly refer this GIF by Microverse.
![pull_request_desc](https://user-images.githubusercontent.com/44057863/170840029-dd11ea02-5663-472d-9b17-138522dc1487.gif)

- [ ] You should use meaningful commit messages. There is only one commit message for this milestone and I could have more commits and the messages can be improved to make it more meaningful that indicates the changes in that commit.
![image](https://user-images.githubusercontent.com/44057863/170840065-3852a5ef-757b-4663-b2b0-b8b7bbe8b021.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 19:26 UTC, gtekle commented on index.html
> +            <section class="contact">
- [ ] The contact section is not part of this milestone. Therefore, kindly move this code into its own PR for upcoming milestones.

2022-05-28 19:26 UTC, gtekle commented on css/styles.css
> +.work {
- [ ] As stated in the project requirement, you should use CSS Grid layout for the project cards container and FlexBox layout to layout individual project cards' content.
![image](https://user-images.githubusercontent.com/44057863/170839465-f0fa26bc-30ac-43f2-9493-ff8bbcef8ad6.png)

2022-05-28 19:26 UTC, gtekle commented on index.html
> +                        <button type="button" class="button">See Project</button>
- [ ] The look of the button in your implementation is a bit different from the design. You should use a 1px width border, padding 12px, border-radius 8px, etc to make it look like the one in the Figma design.
#### Impl
![image](https://user-images.githubusercontent.com/44057863/170839561-3b7d2e55-3162-4d1f-af81-b3f7f6ccc338.png)
#### Design
![image](https://user-images.githubusercontent.com/44057863/170839571-bc493185-1ee6-4c27-8b57-8a6d68d8e9d6.png)

2022-05-28 19:26 UTC, gtekle commented on index.html
> +                <div class="card-tonic">
- [ ] You should a background `#E5E5E5;` of white for the `body` but background color of white for the project cards.
- [ ] The gap between two project cards a bit narrower in your design.
- [ ] Kindly remove the border-shadow in your design of the cards to make it look like in the design.
#### Figma
![image](https://user-images.githubusercontent.com/44057863/170839671-220773e5-8fc2-4c42-9d46-6bd8c64c0fec.png)
#### Impl
![image](https://user-images.githubusercontent.com/44057863/170839658-2bf027aa-0b1d-4d29-b14a-25b7ff1f041a.png)

2022-05-28 19:26 UTC, gtekle commented on index.html
> +            <section class="about-my-self">
- [ ] You should add a gap between the works section and the about me section as in the Figma design.
#### Figma
![image](https://user-images.githubusercontent.com/44057863/170839722-483709d7-09c7-4efd-9168-b01871dbb560.png)

#### Impl
![image](https://user-images.githubusercontent.com/44057863/170839704-20250ea8-8e5a-400a-98e3-255e1a4b6838.png)

2022-05-28 19:26 UTC, gtekle commented on index.html
> +                    </ul>
- [ ] Kindly remove the background color for the headings as in the Figma design.
- [ ] Kindly align the heading text and and the corresponding icons on the left and the right respectively as in the design.
#### Figma
![image](https://user-images.githubusercontent.com/44057863/170839815-9f0891b3-9292-4f82-87f2-77f261d2f308.png)
#### Impl
![image](https://user-images.githubusercontent.com/44057863/170839837-2ab3931b-4fcd-4007-8f0e-890692853e02.png)

2022-05-30 22:23 UTC, Gambit142 reviewed
Hi @looh16 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Your project was invalidated for the following reasons:
- You submitted a previous pull request (That of last week). Kindly create a new pull request and submit the newly created one.
- Your pull request description does not explain vividly the new features or work done in this branch. Kindly make these changes. 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-31 05:58 UTC, closed without merging